export interface ConceptDefinition {
  id: string;
  label: string;
  href: string;
  description?: string;
  priority: 1 | 2 | 3;
  aliases?: string[];
}

export const CONCEPTS: ConceptDefinition[] = [
  {
    id: "decision-packet",
    label: "Decision Packet",
    href: "/docs/contracts",
    description: "Structured output of the Q decision process used for orchestration and user-facing decisions.",
    priority: 1,
    aliases: ["DecisionPacket", "decision packet", "decision"],
  },
  {
    id: "audio-sandbox",
    label: "Audio Sandbox",
    href: "/docs/audio-sandbox/overview",
    description: "Service layer for indexing, feature extraction, and query operations on audio context.",
    priority: 1,
    aliases: ["Sandbox", "sandbox", "audio sandbox"],
  },
  {
    id: "execution-runtime",
    label: "Execution Runtime",
    href: "/docs/execution-runtime/overview",
    description: "Runtime layer that executes approved DAL actions and returns progress and result states.",
    priority: 1,
    aliases: ["runtime", "execution", "execution runtime"],
  },
  {
    id: "comparison",
    label: "Audio Comparison",
    href: "/docs/audio-comparison/overview",
    description: "A/B evaluation layer that detects and summarizes measurable audio differences.",
    priority: 2,
    aliases: ["Comparison System", "comparison", "audio comparison"],
  },
  {
    id: "recommendation",
    label: "Recommendation Engine",
    href: "/docs/recommendation-engine/overview",
    description: "Reasoning output that suggests actions, confidence, and tradeoffs before execution.",
    priority: 2,
    aliases: ["Recommendation", "recommendation", "recommendation engine"],
  },
  {
    id: "orchestration",
    label: "Orchestration",
    href: "/docs/orchestration/overview",
    description: "Control layer that routes agent calls, aggregates evidence, and coordinates state transitions.",
    priority: 3,
    aliases: ["Orchestration Layer", "orchestration", "orchestration layer"],
  },
  {
    id: "dal",
    label: "DAL",
    href: "/docs/dal-integration",
    description: "Typed execution contract generated by Q and consumed by runtime.",
    priority: 1,
    aliases: ["AudioDAL", "audio.dal", "audio dal"],
  },
  {
    id: "audio-memory",
    label: "Audio Memory",
    href: "/docs/audio-memory",
    description: "Timeline and graph history of versions, decisions, and outcomes.",
    priority: 2,
    aliases: ["memory", "memory graph"],
  },
  {
    id: "lifecycle",
    label: "Lifecycle",
    href: "/docs/lifecycle/overview",
    description: "Session timeline from load to repeated execution and review loops.",
    priority: 2,
    aliases: ["session lifecycle", "session"],
  },
  {
    id: "shared-state",
    label: "Shared State",
    href: "/docs/orchestration/shared-state",
    description: "Cross-agent state object used to coordinate orchestration decisions.",
    priority: 2,
    aliases: ["shared audio state"],
  },
  {
    id: "state-machine",
    label: "State Machine",
    href: "/docs/orchestration/state-machine",
    description: "Allowed orchestration/runtime transitions and forbidden paths.",
    priority: 2,
    aliases: ["orchestration state machine", "runtime states"],
  },
  {
    id: "versioning",
    label: "Versioning",
    href: "/docs/audio-comparison/versioning",
    description: "Rules for creating, connecting, and reviewing audio versions.",
    priority: 2,
    aliases: ["version graph", "audio version"],
  },
  {
    id: "q-agent",
    label: "QAgent",
    href: "/docs/q-agent",
    description: "Planning and orchestration layer translating user requests into deterministic actions.",
    priority: 1,
    aliases: ["q agent"],
  },
  {
    id: "user-intent",
    label: "User Intent",
    href: "/docs/intents",
    description: "Detected intent category and confidence used to route the request flow.",
    priority: 1,
    aliases: ["intent", "intent detection"],
  },
  {
    id: "audio-features",
    label: "Audio Features",
    href: "/docs/audio-sandbox/audio-features",
    description: "Extracted measurable attributes used by comparison and recommendation.",
    priority: 1,
    aliases: ["audio features"],
  },
  {
    id: "audio-query",
    label: "Audio Query",
    href: "/docs/audio-sandbox/query-operations",
    description: "Question answering and retrieval over indexed audio/transcript segments.",
    priority: 2,
    aliases: ["audio query", "query operations"],
  },
  {
    id: "decision-with-user",
    label: "Decision With User",
    href: "/docs/decision-with-user",
    description: "User-facing approval gate before executing impactful actions.",
    priority: 1,
    aliases: ["user decision", "approval flow"],
  },
  {
    id: "canvas-ui",
    label: "Canvas UI",
    href: "/docs/audio-comparison/canvas-ui",
    description: "Visual surface for comparison markers, regions, and playback decisions.",
    priority: 2,
    aliases: ["canvas"],
  },
  {
    id: "agent-request",
    label: "AgentRequest",
    href: "/docs/orchestration/communication-model",
    description: "Typed request envelope sent between orchestration agents.",
    priority: 2,
    aliases: ["agent request"],
  },
  {
    id: "agent-response",
    label: "AgentResponse",
    href: "/docs/orchestration/communication-model",
    description: "Typed response envelope returned by orchestration agents.",
    priority: 2,
    aliases: ["agent response"],
  },
  {
    id: "traceability",
    label: "Traceability",
    href: "/docs/orchestration/communication-model",
    description: "Cross-system request tracing via flowId and traceId metadata.",
    priority: 2,
    aliases: ["traceId", "flowId", "trace id", "flow id"],
  },
  {
    id: "tradeoffs",
    label: "Tradeoffs",
    href: "/docs/recommendation-engine/tradeoffs",
    description: "Quality compromises that must be surfaced before user approval.",
    priority: 2,
    aliases: ["tradeoff"],
  },
  {
    id: "confidence",
    label: "Confidence",
    href: "/docs/recommendation-engine/recommendation-model",
    description: "Scored certainty signal used by routing, recommendation, and gating logic.",
    priority: 2,
    aliases: ["confidence score"],
  },
  {
    id: "audio-session",
    label: "Audio Session",
    href: "/docs/lifecycle/session-model",
    description: "Session-level lifecycle state for repeated analyze/execute/review cycles.",
    priority: 2,
    aliases: ["session model", "session state"],
  },
  {
    id: "system-events",
    label: "System Events",
    href: "/docs/lifecycle/system-events",
    description: "Traceable lifecycle events emitted and consumed across the system.",
    priority: 3,
    aliases: ["system event", "system events"],
  },
  {
    id: "audio-intelligence",
    label: "Audio Intelligence",
    href: "/docs/audio-intelligence",
    description: "High-level intelligence layer interpreting features before processing decisions.",
    priority: 2,
    aliases: ["intelligence layer"],
  },
  {
    id: "segment-model",
    label: "Audio Segment Model",
    href: "/docs/audio-sandbox/segment-model",
    description: "Segment contract for bounded audio regions used in scan/query workflows.",
    priority: 3,
    aliases: ["segment model", "segments", "audio segment"],
  },
  {
    id: "transcript-index",
    label: "Transcript Index",
    href: "/docs/audio-sandbox/transcript-index",
    description: "Word-level searchable transcript structure with timing and confidence.",
    priority: 3,
    aliases: ["transcript", "word-level index"],
  },
  {
    id: "lufs-normalization",
    label: "LUFS Normalization",
    href: "/docs/audio-comparison/playback-modes",
    description: "Loudness normalization rule required before A/B switching.",
    priority: 3,
    aliases: ["LUFS", "normalization"],
  },
  {
    id: "comparison-summary",
    label: "Comparison Summary",
    href: "/docs/audio-comparison/comparison-model",
    description: "Aggregated difference count, impact level, and recommended action.",
    priority: 3,
    aliases: ["summary panel", "ComparisonSummary"],
  },
  {
    id: "recommendation-card",
    label: "Recommendation Card",
    href: "/docs/recommendation-engine/ux-presentation",
    description: "User-facing recommendation unit with confidence, impact, and tradeoff visibility.",
    priority: 3,
    aliases: ["card view model", "recommendation card"],
  },
];

function assertConceptRegistryConsistency(concepts: ConceptDefinition[]): void {
  const ids = new Set<string>();
  const labels = new Set<string>();

  for (const concept of concepts) {
    if (ids.has(concept.id)) {
      throw new Error(`Duplicate concept id detected: ${concept.id}`);
    }
    ids.add(concept.id);

    const normalizedLabel = concept.label.toLowerCase();
    if (labels.has(normalizedLabel)) {
      throw new Error(`Duplicate concept label detected: ${concept.label}`);
    }
    labels.add(normalizedLabel);
  }
}

assertConceptRegistryConsistency(CONCEPTS);

export interface CanonicalConceptRegistryItem {
  concept: string;
  description: string;
  canonical_page: string;
  owned_by: string;
}

export const CANONICAL_CONCEPT_REGISTRY: CanonicalConceptRegistryItem[] = [
  { concept: "WaveQ System", description: "Unified multi-layer architecture and documentation model.", canonical_page: "/docs/system", owned_by: "System" },
  { concept: "Layer", description: "Top-level bounded documentation and ownership domain.", canonical_page: "/docs/system", owned_by: "System" },
  { concept: "Flow", description: "Ordered transition path between system stages.", canonical_page: "/docs/system-flow", owned_by: "System" },

  { concept: "QAgent", description: "Reasoning and orchestration layer between client and API.", canonical_page: "/docs/q-agent", owned_by: "QAgent Layer" },
  { concept: "QCore", description: "Central orchestrator module within QAgent core modules.", canonical_page: "/docs/architecture/modules/qagent-core", owned_by: "QAgent Layer" },
  { concept: "Plan", description: "Structured executable action model prepared by QAgent planning stages.", canonical_page: "/docs/architecture/modules/dal", owned_by: "QAgent Layer" },
  { concept: "Intent", description: "Structured user-goal interpretation used to drive planning.", canonical_page: "/docs/architecture/modules/intent-clarification", owned_by: "QAgent Layer" },
  { concept: "Approval", description: "User-gated control boundary before execution handoff.", canonical_page: "/docs/architecture/modules/approval", owned_by: "QAgent Layer" },
  { concept: "DAL", description: "Planning subsystem that converts validated intent into executable and UI plans.", canonical_page: "/docs/architecture/modules/dal", owned_by: "QAgent Layer" },
  { concept: "UAgent", description: "UI-facing execution mediation module in QAgent flow.", canonical_page: "/docs/architecture/modules/uagent", owned_by: "QAgent Layer" },

  { concept: "API Server Layer", description: "Execution orchestration boundary exposing API runtime surfaces.", canonical_page: "/docs/api", owned_by: "API Server Layer" },
  { concept: "Execution Request Envelope", description: "Canonical request entity sent from QAgent to API /run.", canonical_page: "/docs/api", owned_by: "API Server Layer" },
  { concept: "Job", description: "Tracked execution unit managed through orchestration lifecycle.", canonical_page: "/docs/api/job-orchestration", owned_by: "API Server Layer" },
  { concept: "Job Lifecycle", description: "State progression model for job status and progress ownership.", canonical_page: "/docs/api/job-orchestration", owned_by: "API Server Layer" },
  { concept: "Queue", description: "Orchestration staging mechanism for runnable job processing.", canonical_page: "/docs/api/job-orchestration", owned_by: "API Server Layer" },

  { concept: "Execution Layer", description: "Subsystem that translates runnable context into runtime actions and result package.", canonical_page: "/docs/api/execution", owned_by: "API Server Layer" },
  { concept: "Plan Interpreter", description: "Execution module that derives executable action sequence from immutable plan context.", canonical_page: "/docs/api/execution", owned_by: "Execution Layer" },
  { concept: "Action Dispatcher", description: "Execution module that routes actions to runtime/worker executors.", canonical_page: "/docs/api/execution", owned_by: "Execution Layer" },
  { concept: "Result Collector", description: "Execution module that emits the canonical Execution Result Package.", canonical_page: "/docs/api/execution", owned_by: "Execution Layer" },

  { concept: "Versioning", description: "Version lifecycle ownership for result references and history.", canonical_page: "/docs/api/versioning", owned_by: "API Server Layer" },
  { concept: "Version", description: "Immutable versioned output reference in lifecycle history.", canonical_page: "/docs/api/versioning", owned_by: "API Server Layer" },
  { concept: "Artifact", description: "Produced execution output item included in result packaging/version records.", canonical_page: "/docs/api/execution", owned_by: "Execution Layer" },

  { concept: "Client Layer", description: "User-facing layer for interaction and UI/runtime projection.", canonical_page: "/docs/client", owned_by: "Client Layer" },
  { concept: "UI State", description: "Client-owned state model for deterministic interface rendering and updates.", canonical_page: "/docs/client/state-ownership", owned_by: "Client Layer" },
  { concept: "Session", description: "Session-scoped interaction and state continuity context.", canonical_page: "/docs/client/state-ownership", owned_by: "Client Layer" },
];
