import type { DocPageContent } from "@/lib/docs";

export const contractsContent: DocPageContent = {
  slug: "contracts",
  title: "Contracts",
  description:
    "Authoritative TypeScript contracts for Q input, planning, approval, execution handoff, and final output.",
  sections: [
    {
      title: "Contract Lifecycle",
      body: [
        "QIntent is created first from raw user text and context, then wrapped into QInput for planner execution.",
        "QPlan and QPlanStep are produced by the planner and consumed by DAL generation logic.",
        "QExecutionRequest is emitted only after a valid plan exists and optional ApprovalRequest is resolved.",
        "QOutput is produced at the end of the planning cycle and consumed by chat/UI and orchestration logs.",
      ],
    },
    {
      title: "QIntent",
      body: [
        "Created during intent classification before planning starts.",
        "Consumed by the planner and confidence policy.",
      ],
      code: `/** Intent domain supported by Q v1. */
export type QIntentType =
  | "enhance_voice"
  | "remove_noise"
  | "master_track"
  | "normalize_loudness"
  | "trim_silence"
  | "unknown";

/** Optional target scope for processing. */
export type QTargetScope = "full_track" | "selected_region";

export interface QIntent {
  /** Classified intent label. */
  type: QIntentType;
  /** Optional target extracted from prompt or UI context. */
  target?: QTargetScope;
  /** 0..1 confidence score produced by intent parser. */
  confidence: number;
  /** Short explanation used for debugging and traceability. */
  rationale: string;
  /** Terms used as evidence for classification. */
  evidence: string[];
}`,
    },
    {
      title: "QInput",
      body: [
        "Created at request start by API/controller layer.",
        "Consumed by the planner and policy evaluator.",
      ],
      code: `export interface QInput {
  /** Request-scoped unique ID for traceability. */
  requestId: string;
  /** Stable session or conversation identifier. */
  sessionId: string;
  /** Original user message from chat. */
  userText: string;
  /** Optional pre-classified intent from upstream stage. */
  intent?: QIntent;
  /** Optional edit region in milliseconds when user selected timeline range. */
  selectedRegionMs?: {
    startMs: number;
    endMs: number;
  };
  /** Additional context that can affect planning and policy. */
  context?: Record<string, string | number | boolean>;
  /** ISO timestamp captured at ingress. */
  timestamp: string;
}`,
    },
    {
      title: "QPlanStep",
      body: [
        "Created during planner decomposition after intent resolution.",
        "Consumed by DAL transformer and approval policy checks.",
      ],
      code: `export type QPlanStepType =
  | "analyze"
  | "transform"
  | "validate"
  | "render_preview"
  | "apply";

export interface QPlanStep {
  /** Stable unique ID for step references. */
  id: string;
  /** Semantic role of this step in the pipeline. */
  type: QPlanStepType;
  /** Human-readable description for explainability. */
  description: string;
  /** Target scope this step operates on. */
  target: QTargetScope;
  /** Optional ordered dependency list of step IDs. */
  dependsOn?: string[];
  /** Parameters later mapped to DAL action params. */
  params?: Record<string, unknown>;
  /** 0..1 confidence specific to this step. */
  confidence: number;
  /** Whether this step can alter user data. */
  destructive: boolean;
}`,
    },
    {
      title: "QPlan",
      body: [
        "Created after all planning steps are generated and validated.",
        "Consumed by DAL generation and user explainability UI.",
      ],
      code: `export interface QPlan {
  /** Unique plan ID for this request. */
  planId: string;
  /** Main goal statement derived from intent + user phrasing. */
  goal: string;
  /** Ordered execution steps generated by the planner. */
  steps: QPlanStep[];
  /** Average confidence for whole plan, 0..1. */
  overallConfidence: number;
  /** True when plan cannot be executed without explicit approval. */
  requiresApproval: boolean;
  /** Optional risk reasons used in approval UX. */
  approvalReasons?: string[];
}`,
    },
    {
      title: "ApprovalRequest",
      body: [
        "Created only when policy marks plan as risky/destructive.",
        "Consumed by UI approval flow and orchestration gate.",
      ],
      code: `export interface ApprovalRequest {
  /** Correlates approval to a specific plan. */
  planId: string;
  /** Deterministic summary shown to the user. */
  summary: string;
  /** Risk statements that justify approval requirement. */
  reasons: string[];
  /** Expiration time after which approval becomes invalid. */
  expiresAt: string;
}`,
    },
    {
      title: "QExecutionRequest",
      body: [
        "Created after a plan is accepted and DAL is generated.",
        "Consumed by execution orchestrator / D Agent boundary.",
      ],
      code: `export interface QExecutionRequest {
  /** Correlation ID matching input request. */
  requestId: string;
  /** Plan chosen for execution. */
  plan: QPlan;
  /** DAL payload emitted from plan transformer. */
  dal: AudioDAL;
  /** Approval status at handoff time. */
  approved: boolean;
  /** Optional approver identity from product layer. */
  approvedBy?: string;
}`,
    },
    {
      title: "QOutput",
      body: [
        "Created as terminal output of Q planning cycle.",
        "Consumed by chat response renderer, logs, and orchestration state.",
      ],
      code: `export type QStatus = "planned" | "needs_approval" | "rejected";

export interface QOutput {
  /** Correlation ID matching QInput.requestId. */
  requestId: string;
  /** Final intent used by planner. */
  intent: QIntent;
  /** Produced plan for execution handoff. */
  plan: QPlan;
  /** Optional approval payload when required. */
  approvalRequest?: ApprovalRequest;
  /** Human-readable explanation for UI and logs. */
  explanation: string;
  /** Planning status used by orchestrator. */
  status: QStatus;
}`,
    },
    {
      title: "Usage Example",
      body: [
        "Example end-to-end contract composition for one request.",
      ],
      code: `const output: QOutput = {
  requestId: "req_01JQ8N3QY3",
  intent: {
    type: "remove_noise",
    target: "selected_region",
    confidence: 0.92,
    rationale: "User explicitly asked to clean room hiss in selected range.",
    evidence: ["clean", "background noise", "selection"],
  },
  plan: {
    planId: "plan_01JQ8N4H9A",
    goal: "Reduce steady-state background noise while preserving speech clarity.",
    steps: [
      {
        id: "step_1",
        type: "analyze",
        description: "Estimate noise profile from selected region.",
        target: "selected_region",
        confidence: 0.95,
        destructive: false,
      },
      {
        id: "step_2",
        type: "transform",
        description: "Apply moderate denoise with speech protection.",
        target: "selected_region",
        params: { strength: 0.45 },
        confidence: 0.89,
        destructive: true,
        dependsOn: ["step_1"],
      },
    ],
    overallConfidence: 0.92,
    requiresApproval: true,
    approvalReasons: ["Destructive transform on user-selected data"],
  },
  approvalRequest: {
    planId: "plan_01JQ8N4H9A",
    summary: "Apply denoise to selected region with reversible preview first",
    reasons: ["Destructive transform on selected region"],
    expiresAt: "2026-04-04T12:00:00.000Z",
  },
  explanation: "Q prepared a two-step denoise plan and requires approval before apply.",
  status: "needs_approval",
};`,
    },
  ],
};