import type { DocPageContent } from "@/lib/docs";

export const qcoreContent: DocPageContent = {
  slug: "qcore",
  title: "Main QAgent Core Structure",
  description: "Authoritative architectural definition of the QAgent runtime core structure.",
  sections: [
    {
      title: "Main QAgent Core Structure",
      body: [
        "### Overview",
        "QCore is the architectural center of QAgent: a state-aware runtime orchestrator and loop controller.",
        "### Definition",
        "QCore is not the LLM. It uses external reasoning engines through a defined interface layer and keeps execution authority inside the runtime.",
        "### Mission",
        "Control flow, preserve state awareness, route actions between layers, and decide the next valid transition in each loop iteration.",
        "### Central Loop",
        "User input -> QCore -> LLM reasoning -> decision -> module execution -> state update -> QCore.",
        "### Surrounding Layers",
        "LLM Interface Layer, Model Provider Registry, Tool System, State Manager, Flow Controller, and Memory / History Layer.",
        "### Control Boundaries",
        "QCore governs sequencing, routing, and validation gates, while domain execution internals and provider internals remain outside QCore responsibility.",
      ],
    },
    {
      title: "QCore Engine",
      body: [
        "### Overview",
        "QCore Engine is the internal runtime of QAgent. It executes the agent loop and coordinates reasoning with execution flow.",
        "### Core Principle",
        "QCore Engine is a loop-based orchestration system that manages reasoning, decisions, and execution transitions.",
        "### Internal Components",
        "Agent Controller: runs the loop, triggers reasoning cycles, and controls progression.",
        "Decision Engine: interprets LLM outputs and converts them into structured next-step decisions.",
        "Execution Router: maps decisions to tools/modules and routes validated payloads to execution targets.",
        "State Coordinator: maintains internal runtime state and updates context after each step.",
        "### Internal Flow",
        "Input -> Agent Controller -> LLM reasoning -> Decision Engine -> Execution Router -> Modules -> State Coordinator -> loop.",
        "### Interaction with External Layers",
        "Coordinates with LLM Interface Layer (reasoning), Tool System (execution), State Manager (shared state), and Flow Controller (global rules).",
        "### Control Boundaries",
        "Responsible for orchestration, reasoning coordination, and state progression. Not responsible for DSP execution, UI rendering, file handling, or direct model implementation.",
        "### Loop Behavior",
        "Iterative behavior where each transition depends on prior state; continues until completion or user interaction checkpoint.",
        "### Failure Handling (Conceptual)",
        "Invalid decision -> retry reasoning. Missing data -> return to clarification. Execution failure -> fallback or re-route.",
        "### Architectural Summary",
        "QCore Engine is the internal execution system of QAgent, responsible for running the loop, coordinating reasoning, routing execution, and maintaining state progression.",
      ],
    },
    {
      title: "LLM Interface Layer",
      body: [
        "### Core Definition",
        "The LLM Interface Layer is a controlled execution boundary that mediates all communication between QCore and external reasoning engines.",
        "It prepares invocation context, selects model providers, executes calls, validates responses, and returns structured decisions to QCore.",
        "### Context Builder",
        "Prepares the model request context including current stage, user input, system context, tool definitions, and memory when available.",
        "### Model Selector",
        "Chooses the model path per stage, complexity, latency requirements, and cost constraints.",
        "### Invocation Engine",
        "Executes model calls and manages request dispatch, timeout handling, retries, and fallback behavior.",
        "### Response Parser",
        "Interprets LLM output and extracts action intent, selected tool, and next stage signal.",
        "### Validation Layer",
        "Validates response integrity: tool legality, stage validity, and output completeness.",
        "### Decision Formatter",
        "Returns a normalized decision object to QCore with structured output and optional confidence metadata.",
        "### Flow",
        "QCore -> Context Builder -> Model Selector -> Invocation Engine -> LLM -> Response Parser -> Validation Layer -> Decision Formatter -> QCore.",
        "### Input",
        "Stage, context, user input, available tools, and history.",
        "### Output",
        "Next action, selected tool, next stage, optional reasoning, and optional confidence.",
        "### Control Boundary",
        "QCore controls invocation authority and system flow. LLM responses never control flow directly.",
        "Every response must pass validation before re-entering QCore decision flow.",
        "### Multi-Model Strategy",
        "Supports multiple model providers, dynamic model switching, fallback paths, and cost-aware routing.",
        "### Non Responsibilities",
        "This layer does not execute tools, does not mutate state directly, and does not make final system decisions.",
        "### Failure Handling",
        "Invalid response -> reject. Missing required fields -> retry. Timeout -> fallback model path.",
        "### Validation",
        "{\"llm_layer_defined\": true, \"components_separated\": true, \"multi_model_supported\": true, \"validation_enforced\": true, \"safe_execution_boundary\": true}",
      ],
    },
    {
      title: "Model Provider Registry",
      body: [
        "### Overview",
        "The Model Provider Registry is a centralized abstraction layer that enables QCore to work with multiple model providers through a unified interface.",
        "It isolates provider-specific logic while preserving full runtime control over model selection, routing, and fallback behavior.",
        "### Internal Structure",
        "Module Type: Provider Abstraction Layer.",
        "Purpose: dynamic provider/model selection, QCore-provider decoupling, fallback and redundancy, consistent runtime behavior, and cost-latency-performance optimization.",
        "Provider Definitions: provider identity, supported models, capabilities (tools, JSON, streaming), and constraints.",
        "Model Mapping Layer: maps stages to model classes (intent -> fast, planning -> advanced, UI generation -> lightweight).",
        "Selection Engine: selects provider/model using stage, complexity, latency targets, cost, and provider availability.",
        "Fallback Manager: handles retries, provider switching, and degraded execution modes.",
        "Capability Resolver: validates tool support, structured output, and streaming compatibility.",
        "Provider Adapter Layer: normalizes request/response formats and hides provider API differences.",
        "### Flow and Interfaces",
        "QCore -> LLM Interface Layer -> Model Provider Registry -> Selection Engine -> Provider Adapter -> External Model -> Response -> Registry -> LLM Interface -> QCore.",
        "Inputs: stage, context complexity, required capabilities, system constraints (latency/cost), and provider status.",
        "Outputs: selected provider, selected model, execution configuration, and fallback chain.",
        "### Control and Strategy",
        "QCore does not know provider internals and does not select models directly. Provider logic is encapsulated inside the registry.",
        "Supports multiple providers, dynamic switching, fallback routing, and cost-performance optimization.",
        "Does not perform reasoning, interpret model responses, execute tools, or manage system state.",
        "### Failure Handling",
        "Provider unavailability -> fallback. Timeout -> retry or switch provider. Unsupported capability -> reroute to a compatible model path.",
        "### Architectural Summary",
        "The Model Provider Registry is the abstraction layer that keeps QCore provider-agnostic while controlling model selection, execution routing, and fallback behavior through a unified interface.",
        "### Validation",
        "{\"providers_abstracted\": true, \"multi_provider_supported\": true, \"fallback_supported\": true, \"qcore_decoupled\": true, \"unified_interface\": true}",
      ],
    },
    {
      title: "Tool System",
      body: [
        "### Overview",
        "The Tool System is the execution layer of QAgent. It receives validated decisions from QCore and performs real operations such as analysis, transformation, UI generation, or DSP execution.",
        "It does not decide what to do. It only executes approved actions and returns structured outcomes.",
        "### Module Type and Purpose",
        "Module Type: Execution Layer (Modular Tool Runtime).",
        "Purpose: execute actions approved by QCore, provide a modular and extensible runtime, isolate execution from orchestration, enforce consistent structured outputs, and maintain safe controlled behavior.",
        "### Internal Structure",
        "Tool Registry: catalog of tools including tool name, type, supported inputs, expected outputs, and capability definitions.",
        "Tool Resolver: maps decision -> tool, verifies availability, and prepares execution context.",
        "Execution Engine: runs tool logic, manages lifecycle, and supports synchronous/asynchronous execution.",
        "Input Adapter: normalizes QCore payloads into tool-ready input and validates required fields.",
        "Output Formatter: normalizes outputs into enforced schema, standardized result shape, and metadata (status/errors/timing).",
        "Safety Layer: blocks unsafe operations, enforces execution constraints, and prevents invalid tool usage.",
        "### Flow and Interfaces",
        "QCore -> Decision (validated) -> Tool Resolver -> Input Adapter -> Execution Engine -> Tool Execution -> Output Formatter -> QCore.",
        "Inputs: selected tool/action, execution payload, current context, and execution constraints.",
        "Outputs: execution result, structured output, status (success/failure), and metadata (timing/logs/errors).",
        "### Control Boundary and Modular Design",
        "Critical boundary: QCore decides, Tool System executes. Tool System never initiates actions on its own.",
        "Supports plug-and-play tools, independent tool development, extension without QCore changes, and multiple tool categories (analysis/UI/DSP/etc).",
        "### Non Responsibilities and Failure Handling",
        "Non responsibilities: no reasoning, no independent tool selection, no system state management, no flow control.",
        "Failure handling: invalid input -> reject execution. Execution failure -> return structured error. Partial execution -> return safe result.",
        "### Architectural Summary",
        "The Tool System is the execution layer of QAgent, responsible for performing modular actions from QCore decisions while preserving strict separation between decision-making and execution.",
        "### Validation",
        "{\"execution_isolated\": true, \"tools_modular\": true, \"qcore_controls_execution\": true, \"structured_outputs\": true, \"safe_execution\": true}",
      ],
    },
    {
      title: "State Manager",
      body: [
        "### Overview",
        "The State Manager is the persistent runtime memory layer for QAgent operations.",
        "It maintains context required for QCore to route actions, track decisions, and progress reliably through the loop.",
        "QCore reads state before routing and writes state after every validated transition.",
        "### Module Type and Purpose",
        "Module Type: Persistent State Layer (Runtime Context Store).",
        "Purpose: maintain consistent runtime context, store decision state and intermediate results, track progression, enable loop continuity, and provide a reliable source of truth for QCore.",
        "### Internal Structure",
        "Context Store: user input history, processed data, intermediate outputs, and active session data.",
        "Decision State Store: selected actions, chosen tools, optional reasoning snapshots, and decision history.",
        "Progress Tracker: current stage, completed stages, pending stages, and loop iteration state.",
        "State Persistence Layer: persists state across steps, restores state when needed, and preserves consistency across iterations.",
        "State Validator: validates required fields, blocks corrupted state, and enforces schema consistency.",
        "State Access Interface: controlled read/write operations for QCore, including partial updates.",
        "### Flow and Interfaces",
        "QCore -> Read State -> Decision/Routing -> Execute Action -> Update State -> State Manager -> Next Loop.",
        "Inputs: execution results, decision outputs, user input updates, and system signals (stage changes).",
        "Outputs: current context, decision state, progression markers, and validated state snapshots.",
        "### Control Boundary and State Characteristics",
        "Critical boundary: QCore reads before routing and writes after validated transitions. State Manager does not initiate state changes independently.",
        "State characteristics: consistency across iterations, persistence across loops, structured validated data, and recoverability after failure.",
        "### Non Responsibilities and Failure Handling",
        "Non responsibilities: no reasoning, no tool execution, no flow control, and no action selection.",
        "Failure handling: invalid state -> reject or repair. Missing data -> fallback or clarification request. Corrupted state -> reset or rollback.",
        "### Architectural Summary",
        "The State Manager is the persistent runtime memory layer of QAgent, maintaining context, tracking decisions, and ensuring consistent progression across agent loops.",
        "### Validation",
        "{\"state_persistent\": true, \"context_managed\": true, \"progress_tracked\": true, \"qcore_reads_and_writes\": true, \"state_validated\": true}",
      ],
    },
    {
      title: "Flow Controller",
      body: [
        "### Overview",
        "The Flow Controller is the transition validation layer of QAgent.",
        "It ensures every QCore transition is valid, properly sequenced, and aligned with the defined execution flow.",
        "QCore consults it before transitions to prevent invalid, premature, or unsafe actions.",
        "### Module Type and Purpose",
        "Module Type: Transition Control Layer (Flow Guard System).",
        "Purpose: enforce valid stage transitions, block out-of-order actions, maintain deterministic behavior, ensure loop consistency, and preserve orchestration integrity.",
        "### Internal Structure",
        "Transition Map: allowed stage-to-stage mappings, restricted transitions, and conditional transitions.",
        "Validation Engine: validates current stage, requested next stage, system constraints, and required conditions.",
        "Rule Engine: applies sequencing rules, dependency rules, and execution constraints.",
        "Guard Layer: blocks premature execution, enforces approval gates, and prevents invalid tool usage.",
        "Recovery Handler: redirects invalid attempts to valid stages, requests clarification, or triggers retries.",
        "Transition Logger: records transitions for traceability, debugging, and operational analysis.",
        "### Flow and Interfaces",
        "QCore -> Proposed Transition -> Flow Controller -> Validation Engine -> Rule Engine -> Guard Layer -> Approved/Rejected -> QCore.",
        "Inputs: current state, requested next stage, execution context, system rules, and decision output.",
        "Outputs: transition approval/rejection, corrected next stage (when needed), validation results, and transition metadata.",
        "### Control Boundary and System Behavior",
        "Critical boundary: QCore proposes transitions, Flow Controller validates them. Flow Controller never initiates transitions independently.",
        "System behavior: strict sequencing, deterministic execution, invalid transition prevention, and controlled progression through the flow.",
        "### Non Responsibilities and Failure Handling",
        "Non responsibilities: no reasoning, no tool execution, no direct state management, and no action selection.",
        "Failure handling: invalid transition -> reject. Premature action -> block. Missing dependency -> redirect. Inconsistent state -> trigger recovery.",
        "### Architectural Summary",
        "The Flow Controller is the guardrail layer of QAgent, ensuring transitions between runtime states remain valid, controlled, and consistent with the defined execution flow.",
        "### Validation",
        "{\"transitions_validated\": true, \"invalid_actions_blocked\": true, \"flow_deterministic\": true, \"qcore_controlled\": true, \"system_integrity_preserved\": true}",
      ],
    },
    {
      title: "Memory / History Layer",
      body: [
        "### Overview",
        "The Memory & History Layer is the contextual intelligence layer of QAgent.",
        "It stores interaction lineage, decisions, execution outcomes, and version history so QCore can operate with awareness across repeated loops and evolving workflows.",
        "### Module Type and Purpose",
        "Module Type: Context Persistence Layer (Historical Memory System).",
        "Purpose: preserve interaction history across sessions, maintain decision and execution lineage, support context-aware loops, store versioned outcomes (including audio workflows), and enable iterative continuity.",
        "### Internal Structure",
        "Interaction History: user inputs, system outputs, clarification steps, and timeline continuity.",
        "Decision History: selected actions, tool choices, stage transitions, and optional reasoning snapshots.",
        "Execution History: tool outputs, execution metadata, and success/failure states.",
        "Audio Memory: timeline of audio changes, DSP chain evolution, waveform states, and processing history (reference: /docs/audio-memory).",
        "Version History: version snapshots, delta/change tracking, and rollback support.",
        "Session Lineage: session identity, linked sessions, and continuation context.",
        "Memory Index / Retrieval Layer: contextual lookup, relevance filtering, and selection of memory slices for QCore.",
        "### Flow and Interfaces",
        "QCore -> Request Context -> Memory Layer -> Retrieve Relevant History -> Provide Context -> QCore Decision Loop -> Write New Data -> Memory Updated.",
        "Inputs: user interactions, decisions, execution results, version updates, and session data.",
        "Outputs: contextual history, decision lineage, execution traces, version snapshots, and relevant memory for reasoning.",
        "### Control Boundary and System Behavior",
        "Critical boundary: QCore consumes memory before decisions and writes memory after each loop. Memory Layer does not initiate actions.",
        "System behavior: context-aware reasoning support, continuity across loops, iterative refinement, historical traceability, and memory-based decision support.",
        "### Non Responsibilities and Failure Handling",
        "Non responsibilities: no reasoning, no tool execution, no flow control, and no transition validation.",
        "Failure handling: missing memory -> fallback to minimal context. Corrupted history -> reset or partial recovery. Irrelevant history -> filtered retrieval.",
        "### Architectural Summary",
        "The Memory & History Layer is the contextual backbone of QAgent, enabling persistent awareness, historical tracking, and continuity across iterative execution cycles.",
        "### Validation",
        "{\"memory_persistent\": true, \"history_tracked\": true, \"audio_memory_supported\": true, \"versioning_supported\": true, \"context_awareness_enabled\": true}",
      ],
    },
  ],
};
