import type { DocPageContent } from "@/lib/docs";

export const qcoreContent: DocPageContent = {
  slug: "qcore",
  title: "Main QAgent Core Structure",
  description: "Authoritative architectural definition of the QAgent runtime core structure.",
  sections: [
    {
      title: "Main QAgent Core Structure",
      body: [
        "### Overview",
        "QCore is the architectural center of QAgent: a state-aware runtime orchestrator and loop controller.",
        "### Definition",
        "QCore is not the LLM. It uses external reasoning engines through a defined interface layer and keeps execution authority inside the runtime.",
        "### Mission",
        "Control flow, preserve state awareness, route actions between layers, and decide the next valid transition in each loop iteration.",
        "### Central Loop",
        "User input -> QCore -> LLM reasoning -> decision -> module execution -> state update -> QCore.",
        "### Surrounding Layers",
        "LLM Interface Layer, Model Provider Registry, Tool System, State Manager, Flow Controller, and Memory / History Layer.",
        "### Control Boundaries",
        "QCore governs sequencing, routing, and validation gates, while domain execution internals and provider internals remain outside QCore responsibility.",
      ],
    },
    {
      title: "QCore Engine",
      body: [
        "### Main QAgent Core Structure",
        "### QCore Engine",
        "### LLM Interface Layer",
        "### Model Provider Registry",
        "### Tool System",
        "### State Manager",
        "### Flow Controller",
        "### Memory / History Layer",
      ],
    },
    {
      title: "LLM Interface Layer",
      body: [
        "### Core Definition",
        "The LLM Interface Layer is a controlled execution boundary that mediates all communication between QCore and external reasoning engines.",
        "It prepares invocation context, selects model providers, executes calls, validates responses, and returns structured decisions to QCore.",
        "### Context Builder",
        "Prepares the model request context including current stage, user input, system context, tool definitions, and memory when available.",
        "### Model Selector",
        "Chooses the model path per stage, complexity, latency requirements, and cost constraints.",
        "### Invocation Engine",
        "Executes model calls and manages request dispatch, timeout handling, retries, and fallback behavior.",
        "### Response Parser",
        "Interprets LLM output and extracts action intent, selected tool, and next stage signal.",
        "### Validation Layer",
        "Validates response integrity: tool legality, stage validity, and output completeness.",
        "### Decision Formatter",
        "Returns a normalized decision object to QCore with structured output and optional confidence metadata.",
        "### Flow",
        "QCore -> Context Builder -> Model Selector -> Invocation Engine -> LLM -> Response Parser -> Validation Layer -> Decision Formatter -> QCore.",
        "### Input",
        "Stage, context, user input, available tools, and history.",
        "### Output",
        "Next action, selected tool, next stage, optional reasoning, and optional confidence.",
        "### Control Boundary",
        "QCore controls invocation authority and system flow. LLM responses never control flow directly.",
        "Every response must pass validation before re-entering QCore decision flow.",
        "### Multi-Model Strategy",
        "Supports multiple model providers, dynamic model switching, fallback paths, and cost-aware routing.",
        "### Non Responsibilities",
        "This layer does not execute tools, does not mutate state directly, and does not make final system decisions.",
        "### Failure Handling",
        "Invalid response -> reject. Missing required fields -> retry. Timeout -> fallback model path.",
        "### Validation",
        "{\"llm_layer_defined\": true, \"components_separated\": true, \"multi_model_supported\": true, \"validation_enforced\": true, \"safe_execution_boundary\": true}",
      ],
    },
    {
      title: "Model Provider Registry",
      body: [
        "Provider abstraction used by QCore to select model backends and fallback paths.",
        "Keeps provider-specific details outside QCore while preserving consistent runtime control.",
      ],
    },
    {
      title: "Tool System",
      body: [
        "Execution layer for modular actions approved by QCore.",
        "QCore decides if and when tools run; Tool System performs the operation and returns structured outcomes.",
      ],
    },
    {
      title: "State Manager",
      body: [
        "Persistent state layer storing runtime context, decision state, and progression markers.",
        "QCore reads state before routing and writes state after each validated transition.",
      ],
    },
    {
      title: "Flow Controller",
      body: [
        "Transition guardrail layer that enforces allowed movement between runtime states.",
        "QCore uses Flow Controller to keep orchestration deterministic and prevent invalid or premature actions.",
      ],
    },
    {
      title: "Memory / History Layer",
      body: [
        "Context layer for prior interactions, decisions, and session lineage.",
        "QCore consumes this history to remain context-aware across repeated loops and to preserve continuity in decision-making.",
      ],
    },
  ],
};
