import type { DocPageContent } from "@/lib/docs";

export const recommendationEngineModelContent: DocPageContent = {
  slug: "recommendation-engine/recommendation-model",
  title: "Recommendation Model",
  description: "Typed recommendation object for action proposals, impact expectations, and confidence.",
  sections: [
    {
      title: "AudioRecommendation Contract",
      body: [
        "Recommendation must include actionable steps and expected impact statements.",
        "Tradeoffs are optional but should be provided when side effects are likely.",
      ],
      code: `interface AudioRecommendation {
  id: string
  title: string
  description: string
  actions: string[]
  expectedImpact: string[]
  tradeoffs?: string[]
  confidence: number
}`,
    },
    {
      title: "Field Semantics",
      body: [
        "id: unique recommendation identifier generated by recommendation layer and consumed by decision/audit logs.",
        "title: short user-facing label generated by reasoning layer and consumed by recommendation card UI.",
        "description: compact explanation generated by reasoning layer and consumed by user confirmation flow.",
        "actions: executable option list generated by recommendation planner and consumed by decision-with-user.",
        "expectedImpact: projected outcomes generated from evidence mapping and consumed by UI + user decision.",
        "tradeoffs: downside list generated when relevant and consumed by UI warning area.",
        "confidence: numeric confidence score generated by recommendation scorer and consumed by gating rules.",
      ],
    },
    {
      title: "Recommended Extensions",
      body: [
        "Evidence should be attached so recommendations are traceable to analysis artifacts.",
        "Priority is recommended for deterministic ordering when multiple recommendations are available.",
      ],
      code: `interface AudioRecommendationEvidence {
  source: 'audio_features' | 'comparison' | 'history' | 'user_intent'
  referenceIds?: string[]
  note: string
}

interface AudioRecommendationV2 extends AudioRecommendation {
  evidence: AudioRecommendationEvidence[]
  priority: 'low' | 'medium' | 'high'
}`,
    },
  ],
};
