import { DocsContent } from "@/components/layout/DocsContent";
import { ClientCanvasFlowDiagram } from "@/components/ui/ClientCanvasFlowDiagram";

export default function ClientCanvasUiPage() {
  return (
    <DocsContent>
    <main className="space-y-8">
      <section className="space-y-2">
        <h1 className="text-3xl font-semibold">Canvas UI — Overview</h1>
        <p className="text-base text-[var(--muted)]">The Canvas UI is the visual execution interface of WaveQ.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Purpose</h2>
        <p className="text-[var(--muted)]">
          The Canvas UI is the visual execution interface of WaveQ, powered by a dynamic Gen UI layer driven by QAgent (UAgent).
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Role in the System</h2>
        <p className="text-[var(--muted)]">The Canvas UI is the visual representation of system execution.</p>
        <p className="text-[var(--muted)]">
          The Canvas does not only display execution - it dynamically renders UI based on structured plans generated by QAgent.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Interaction Flow</h2>
        <ClientCanvasFlowDiagram />
        <pre className="overflow-x-auto rounded-md border border-[var(--border)] bg-slate-950/40 p-4 text-sm text-slate-200">
{`QAgent Plan -> Canvas UI -> User Interaction -> Client Runtime -> Visual Update`}
        </pre>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Core Responsibilities</h2>
        <div className="space-y-2 text-[var(--muted)]">
          <p>
            <span className="font-semibold text-slate-100">1. Pipeline Visualization</span>: render processing steps as visual blocks, including
            execution order and relationships.
          </p>
          <p>
            <span className="font-semibold text-slate-100">2. Dynamic Gen UI Rendering</span>: dynamically generate UI components from QAgent output
            (UAgent-driven) and keep layout aligned with structured UI plans.
          </p>
          <p>
            <span className="font-semibold text-slate-100">3. Visual State Reflection</span>: reflect system state and execution visually, including
            idle/running/completed and active pipeline steps.
          </p>
          <p>
            <span className="font-semibold text-slate-100">4. User Interaction</span>: allow pipeline block selection and trigger execution-related
            actions through approved controls.
          </p>
          <p>
            <span className="font-semibold text-slate-100">5. Feedback Loop</span>: reflect execution outcomes and keep visuals synchronized in
            real-time.
          </p>
        </div>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Boundaries (Does Not Do)</h2>
        <ul className="list-disc space-y-1 pl-6 text-[var(--muted)]">
          <li>Build execution plans</li>
          <li>Interpret user intent</li>
          <li>Execute processing logic</li>
          <li>Manage job queues</li>
          <li>Contain business logic</li>
        </ul>
        <p className="text-[var(--muted)]">It is a pure visualization and interaction layer.</p>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold">Interaction with QAgent</h2>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Input from QAgent</p>
          <pre className="overflow-x-auto rounded-md border border-[var(--border)] bg-slate-950/40 p-4 text-sm text-slate-200">{`{
  "plan": [...],
  "uiPlan": [...],
  "status": "running"
}`}</pre>
        </div>
        <p className="text-[var(--muted)]">
          Receives a structured plan, renders it as a visual pipeline, updates UI by execution state, and does not alter plan logic.
        </p>
        <p className="text-[var(--muted)]">Rendering is driven by <span className="font-mono">uiPlan</span>, not by the execution plan directly.</p>
        <p className="text-[var(--muted)]">
          The execution plan must never be used directly for rendering decisions.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-2xl font-semibold">UI Plan Schema</h2>
        <p className="text-[var(--muted)]">Define the structure used by QAgent to generate UI dynamically.</p>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Core Structure</p>
          <pre className="overflow-x-auto rounded-md border border-[var(--border)] bg-slate-950/40 p-4 text-sm text-slate-200">{`{
  "uiPlan": {
    "version": "1.0",
    "layout": [],
    "blocks": [],
    "metadata": {}
  }
}`}</pre>
        </div>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Layout</p>
          <pre className="overflow-x-auto rounded-md border border-[var(--border)] bg-slate-950/40 p-4 text-sm text-slate-200">{`{
  "layout": [
    { "id": "main_waveform", "type": "waveform", "region": "main" },
    { "id": "pipeline", "type": "pipeline", "region": "bottom" }
  ]
}`}</pre>
        </div>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Blocks</p>
          <pre className="overflow-x-auto rounded-md border border-[var(--border)] bg-slate-950/40 p-4 text-sm text-slate-200">{`{
  "blocks": [
    {
      "id": "noise_reduction",
      "type": "effect",
      "label": "Noise Reduction",
      "status": "idle",
      "params": { "amount": 0.5 }
    },
    {
      "id": "eq",
      "type": "effect",
      "label": "EQ",
      "status": "ready",
      "params": { "low": 0, "mid": 1, "high": 2 }
    }
  ]
}`}</pre>
        </div>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Metadata</p>
          <pre className="overflow-x-auto rounded-md border border-[var(--border)] bg-slate-950/40 p-4 text-sm text-slate-200">{`{
  "metadata": {
    "status": "ready",
    "duration": 120,
    "sampleRate": 44100
  }
}`}</pre>
        </div>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Full Example</p>
          <pre className="overflow-x-auto rounded-md border border-[var(--border)] bg-slate-950/40 p-4 text-sm text-slate-200">{`{
  "uiPlan": {
    "version": "1.0",
    "layout": [
      { "id": "waveform", "type": "waveform", "region": "main" },
      { "id": "pipeline", "type": "pipeline", "region": "bottom" }
    ],
    "blocks": [
      {
        "id": "noise",
        "type": "effect",
        "label": "Remove Noise",
        "status": "ready",
        "params": { "strength": 0.7 }
      }
    ],
    "metadata": {
      "status": "ready"
    }
  }
}`}</pre>
        </div>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Canvas Behavior</p>
          <pre className="overflow-x-auto rounded-md border border-[var(--border)] bg-slate-950/40 p-4 text-sm text-slate-200">{`render(uiPlan) {
  renderLayout(uiPlan.layout)
  renderBlocks(uiPlan.blocks)
}`}</pre>
        </div>
        <p className="text-[var(--muted)]">Key Rule: Rendering is driven ONLY by uiPlan.</p>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Block Types</p>
          <ul className="list-disc space-y-1 pl-6 text-[var(--muted)]">
            <li>effect: EQ, Compression, Noise</li>
            <li>control: sliders, knobs</li>
            <li>waveform: audio visualization</li>
            <li>status: loading, processing</li>
            <li>action: buttons, export</li>
          </ul>
        </div>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Constraints</p>
          <ul className="list-disc space-y-1 pl-6 text-[var(--muted)]">
            <li>No UI hardcoding</li>
            <li>No rendering from execution plan</li>
            <li>UI must follow schema strictly</li>
            <li>No direct coupling from Canvas rendering to DSP</li>
          </ul>
        </div>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Responsibilities</p>
          <ul className="list-disc space-y-1 pl-6 text-[var(--muted)]">
            <li>QAgent: generates uiPlan</li>
            <li>Canvas: renders uiPlan</li>
          </ul>
        </div>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Future Extension</p>
          <pre className="overflow-x-auto rounded-md border border-[var(--border)] bg-slate-950/40 p-4 text-sm text-slate-200">{`{
  "interactions": {
    "onChange": "update_param",
    "onClick": "trigger_execution"
  }
}`}</pre>
        </div>
        <div className="space-y-1">
          <p className="text-sm font-semibold text-slate-100">Integration with Existing Client Pipeline</p>
          <p className="text-[var(--muted)]">
            This schema aligns directly with <span className="font-mono">buildAgentUIPlan(...)</span>,{" "}
            <span className="font-mono">resolveUIPlanBlocks(...)</span>, and <span className="font-mono">audio-canvas-runtime.tsx</span>.
          </p>
        </div>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Interaction with Client Runtime</h2>
        <p className="text-[var(--muted)]">
          Receives playback state, synchronizes waveform with audio output, and updates visual status in real-time.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Integration Note</h2>
        <p className="text-[var(--muted)]">
          Canvas rendering is driven by <span className="font-mono">uiPlan</span> generated by QAgent and synchronized with Client Runtime.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Design Principles</h2>
        <ul className="list-disc space-y-1 pl-6 text-[var(--muted)]">
          <li>Visual clarity: pipeline readable at a glance</li>
          <li>Immediate feedback: changes reflected instantly</li>
          <li>Consistency with Chat: no divergence between layers</li>
          <li>UI is generated dynamically (Gen UI), not statically defined</li>
          <li>Non-destructive interaction: confirmation required for state-changing actions</li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Capabilities</h2>
        <ul className="list-disc space-y-1 pl-6 text-[var(--muted)]">
          <li>Visual pipeline rendering</li>
          <li>Waveform visualization</li>
          <li>Real-time execution feedback</li>
          <li>Interactive block selection</li>
          <li>Execution state awareness</li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Mental Model</h2>
        <p className="text-[var(--muted)]">Canvas UI = Visual Execution Map + Gen UI System.</p>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Connected Components</h2>
        <ul className="list-disc space-y-1 pl-6 text-[var(--muted)]">
          <li>Chat UI (intent and commands)</li>
          <li>QAgent (plan generation)</li>
          <li>UAgent (Gen UI controller inside QAgent)</li>
          <li>Client Runtime (audio playback and state)</li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Future Extensions</h2>
        <ul className="list-disc space-y-1 pl-6 text-[var(--muted)]">
          <li>Drag-and-drop pipeline editing</li>
          <li>Real-time parameter tuning</li>
          <li>Multi-track editing</li>
          <li>Visual automation curves</li>
          <li>Collaborative canvas</li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-2xl font-semibold">Summary</h2>
        <p className="text-[var(--muted)]">
          Canvas UI is the visual layer of execution, the bridge between plan and perception, and the working surface of the system.
        </p>
      </section>
    </main>
    </DocsContent>
  );
}
